### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by tangshangpeng** [three-shui/vue-rabbit#1]
哥们哥们，我想问一下，我在那个面包屑导航那里我没办法获得name的值，而且他报错：<error>TypeError: Cannot set properties of null (setting 'exmid')</error>，我不知道怎么解决，想来请教一下你

**Comment by tangshangpeng** [comment]
import httpInstance from '@/utils/http'

 export function getCategoryDataAPI(id) {
   return httpInstance ({
    url: '/category',
    params:{
        id
    }
   })
}这个是那个封装接口函数


<script setup>
  import { getCategoryDataAPI } from '@/apis/category'
  import { useRoute } from 'vue-router'
  import {onMounted, ref} from 'vue'

  const categoryData = ref({})
  const route = useRoute()
  const getCategory = async () => {
    // 如何在setup中获取路由参数 useRoute() -> route 等价于this.$route
    const res = await getCategoryDataAPI(route.params.id)
    categoryData.value = res.result
  }
onMounted(()=>getCategory())
</script>这个是在组件内调用函数，我代码和老师讲的时候一样的，但是就是报错

**Comment by tangshangpeng** [comment]
哥们，我刚才把代码改成和你一样的还是在报错 TypeError: Cannot set properties of null (setting 'exmid')，我觉得可能数据的url的问题

**Comment by tangshangpeng** [comment]
我解决了 ，哥们，是因为浏览器的插件的·问题，我把所有插件都禁用后就可以了

**Comment by three-shui** [comment]
好的，解决了就行，下次遇到问题可以继续提，加油！！！

**Comment by tangshangpeng** [comment]
> 好的，解决了就行，下次遇到问题可以继续提，加油！！！

欧克欧克
